### ISSUE TITLE
Check ssl.what.cd when what.cd is down

### ISSUE THREAD

**Issue by dharb** [britishtea/whatcd#1]
Hey man,

First of all I want to give you a huuuuuge thanks for writing this, and then another one for updating it. Really though, great work.

I've noticed that a lot of the time https://what.cd will be unresponsive, but https://ssl.what.cd will be working correctly. What I've done to get around this is use an environment variable to determine whether or not to hit the ssl site. Check it out:

```
def initialize(ssl = false, username = nil, password = nil)
  url = ssl ? "https://ssl.what.cd" : "https://what.cd"
  @connection = Faraday.new(:url => url) do |builder|
    builder.request :url_encoded
    builder.use :cookie_jar
    builder.adapter Faraday.default_adapter
  end

  unless username.nil? || password.nil?
    authenticate username, password 
  end
end
```

Then since I'm using this in a rake task, I use:

```
task :what => :environment do
  client = WhatCD::Client.new ENV['ssl'], "user", "password"
end
```

and call it from command line with rake what ssl=true if I want to try the ssl server, otherwise call it normally.

If this is something you'd like in the project, I'd be happy to update tests/readme and make a pull request.

**Comment by britishtea** [comment]
I like the suggestion to fall back on ssl.what.cd when what.cd is unresponsive. I don't really like the current implementation, but I'd not be against something like this.

``` ruby
client = WhatCD::Client.new "username", "password"
client.fallback_host = "https://ssl.what.cd"

# ...
```

I'd like to hear your feedback :)
