### ISSUE TITLE
Bad conditional in fetch function?

### ISSUE THREAD

**Issue by x0x01x** [britishtea/whatcd#2]

**Comment by x0x01x** [comment]
Instead of checking for "302", I believe the conditional should check for 302 (Integer, not String). Otherwise, instead of raising AuthError, the function raises APIError. Let me know if I've misunderstood, and thanks!

**Comment by britishtea** [comment]
Yes, you're right. I've applied a fix and released a new version (0.2.1). Thanks for reporting :)

**Comment by x0x01x** [comment]
Thanks.
